"""Devanagari words of the introduction, typeset with XeLaTeX for the pdfLaTeX build.

Writes one cropped PDF per word here, and ../../defines/devanagari_words.tex with the
UTF-16BE hex of each word, which \\devword{<name>} (defines/Commands.tex) attaches as
ActualText so the PDF text layer copies and searches as real Devanagari.
Every PDF spans the same box, 0.3em below to 1.05em above the baseline.
Run: python3 figures/devanagari/make_devanagari.py  (from the thesis root or anywhere)
"""
import subprocess
from pathlib import Path

WORDS = {
    "vaisesikasutra": "वैशेषिक सूत्र",
    "anu": "अणु",
    "paramanu": "परमाणु",
    "dharma": "धर्म",
    "moksha": "मोक्ष",
    "nirvana": "निर्वाण",
}
HERE = Path(__file__).resolve().parent
TEMPLATE = r"""\documentclass[12pt, border=0pt]{standalone}
\usepackage{fontspec}
\newfontfamily\devfont[Script=Devanagari]{NewComputerModern 10 Devanagari}
\begin{document}
\devfont\rule[-0.3em]{0pt}{1.35em}%s
\end{document}
"""

defs = ["% Generated by figures/devanagari/make_devanagari.py -- do not edit.\n"]
for name, word in WORDS.items():
    tex = HERE / f"{name}.tex"
    tex.write_text(TEMPLATE % word, encoding="utf-8")
    subprocess.run(["xelatex", "-interaction=nonstopmode", "-halt-on-error", tex.name],
                   cwd=HERE, check=True, stdout=subprocess.DEVNULL)
    for ext in (".tex", ".aux", ".log"):
        (HERE / f"{name}{ext}").unlink(missing_ok=True)
    hexstr = word.encode("utf-16-be").hex().upper()
    defs.append(f"\\expandafter\\def\\csname devhex@{name}\\endcsname{{{hexstr}}}% {word}\n")

(HERE.parent.parent / "defines" / "devanagari_words.tex").write_text("".join(defs), encoding="utf-8")
print("wrote", ", ".join(f"{n}.pdf" for n in WORDS))
